### ISSUE TITLE
Two of the Celsius unit tests are expecting incorrect values

### ISSUE THREAD

**Issue by cswike** [devadvent/puzzle-18#1]
The test suite expects "25°C with a wind of 10km/h should be a windchill of: 28°C", however using the formula that was linked in the README the actual, non-rounded return value is 26.55077.

Similarly, the test suite expects "-20°C with a wind of 45km/h should be a windchill of: -36°C", however using the formula that was linked in the README the actual, non-rounded return value is -34.79717.

Links to calculations below - feel free to check my work, I pasted directly from [https://sciencing.com/calculate-wind-chill-factor-5981683.html](https://sciencing.com/calculate-wind-chill-factor-5981683.html) but I still could have made an error substituting out the variables.

[25°C with a wind of 10km/h](https://www.wolframalpha.com/input/?i=13.12+%2B+0.6215%2825%29+%E2%80%93+11.37%2810%5E0.16%29+%2B+0.3965%2825%29%2810%5E0.16%29)

[-20°C with a wind of 45km/h](https://www.wolframalpha.com/input/?i=13.12+%2B+0.6215%28-20%29+%E2%80%93+11.37%2845%5E0.16%29+%2B+0.3965%28-20%29%2845%5E0.16%29)

Output from yarn test:

 FAIL  tests/windchill.test.js
  ● 25°C with a wind of 10km/h should be a windchill of: 28°C

    expect(received).toBe(expected) // Object.is equality

    Expected: 28
    Received: 27

      25 | restMap.forEach(({ temperature, windSpeed, units, result }) => {
      26 |     test(`${temperature}°C with a wind of ${windSpeed}km/h should be a windchill of: ${result}°C`, () => {
    > 27 |         expect(calculateWindchill(temperature, windSpeed)).toBe(result)
         |                                                            ^
      28 |     })
      29 | })
      30 |

      at Object.<anonymous> (tests/windchill.test.js:27:60)

  ● -20°C with a wind of 45km/h should be a windchill of: -36°C

    expect(received).toBe(expected) // Object.is equality

    Expected: -36
    Received: -35

      25 | restMap.forEach(({ temperature, windSpeed, units, result }) => {
      26 |     test(`${temperature}°C with a wind of ${windSpeed}km/h should be a windchill of: ${result}°C`, () => {
    > 27 |         expect(calculateWindchill(temperature, windSpeed)).toBe(result)
         |                                                            ^
      28 |     })
      29 | })
      30 |

      at Object.<anonymous> (tests/windchill.test.js:27:60)

**Comment by cswike** [comment]
FWIW I also doubled-checked with the National Weather Service. They say "a Wind Chill value cannot be calculated for temperatures greater than 10.0 degrees Celsius" so the first example can't be verified there, but for the second example, -20°C with a wind speed of 45k/h returns -34.8°C.

[https://www.weather.gov/epz/wxcalc_windchill](https://www.weather.gov/epz/wxcalc_windchill)

I did verify the first test result here: [http://www.csgnetwork.com/windchillcalc.html](http://www.csgnetwork.com/windchillcalc.html) - which returned 27°C  for a temperature of 25°C with a wind speed of 10KmPH.

**Comment by bob-fornal** [comment]
I saw the same issues for both temperatures; applied a HACK in my code to pass the tests.

**Comment by cswike** [comment]
Marc has since [acknowledged the error on Twitter](https://twitter.com/themarcba/status/1472212034553098252) and says he’ll manually check the solutions. 

You can also edit tests/windchill.test.js to fix the values - under const restMap change the ‘result’ value on the 1st and 5th lines so they read as follows:

`{ temperature: 25, windSpeed: 10, result: 27 }, `
`{ temperature: -20, windSpeed: 45, result: -35 },`


(and don’t use this knowledge for evil! Play fair 😉)
